### ISSUE TITLE
brazil js?

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/RawWebGL#6]
@mrdoob.  Hey, I was wondering if you're going to be presenting about Three.js at Brazil JS?  I'm going to be speaking as well, barring any visa hiccups.  I was thinking about reworking this presentation to be more about an introduction to graphics programming with the WebGL API.  That would be possibly lower level (talking about attributes, uniforms, buffers, etc) and then after seeing how monotonous it is, the audience would be able to appreciate the higher levels of abstraction (cameras, scenes, materials, etc) provided by Three.js during your talk?  I really don't want to step on any toes, and am happy to talk about something else if you prefer (deferring all graphics talk to you).  What are your thoughts?

**Comment by mrdoob** [comment]
That sounds great to me! :)

Yeah I was going to talk about three.js. Focusing a bit more on the editor this time.
